name: tests
on:
  workflow_dispatch: null
  push:
    branches:
      - main
  pull_request: null

concurrency:
  group: cf-autotick-bot-test-package-feedstock
  cancel-in-progress: false

jobs:
  tests:
    runs-on: ubuntu-latest
    name: tests
    steps:
      - name: update feedstock version
        id: update
        uses: $/
        with:
          feedstock: cf-autotick-bot-test-package-feedstock
          version: "0.13"
          github-token: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}
          automerge: false

      - name: close pr
        run: |
          gh pr close \
          https://github.com/conda-forge/cf-autotick-bot-test-package-feedstock/pull/${{ steps.update.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}

      - name: checkout fork
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: conda-forge-admin/cf-autotick-bot-test-package-feedstock
          path: cf-autotick-bot-test-package-feedstock
          token: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}

      - name: delete pr branch
        run: |
          pushd cf-autotick-bot-test-package-feedstock
          git push origin --delete conda-forge-admin/update-feedstock-version
          popd
        env:
          GH_TOKEN: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}

  tests-with-two-tokens:
    runs-on: ubuntu-latest
    name: tests with two tokens
    needs: tests
    steps:
      - name: update feedstock version
        id: update
        uses: $/
        with:
          feedstock: cf-autotick-bot-test-package-feedstock
          version: "0.13"
          github-token: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}
          github-token-for-fork: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}
          automerge: false

      - name: close pr
        run: |
          gh pr close \
          https://github.com/conda-forge/cf-autotick-bot-test-package-feedstock/pull/${{ steps.update.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}

      - name: checkout fork
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: conda-forge-admin/cf-autotick-bot-test-package-feedstock
          path: cf-autotick-bot-test-package-feedstock
          token: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}

      - name: delete pr branch
        run: |
          pushd cf-autotick-bot-test-package-feedstock
          git push origin --delete conda-forge-admin/update-feedstock-version
          popd
        env:
          GH_TOKEN: ${{ secrets.CF_ADMIN_GITHUB_TOKEN }}

